// mutations.js — proves the slice tests BITE: applies each named mutation to a
// COPY of the source (a mirror under .tmp/ — the source is never edited, so a
// kill mid-run cannot leave it mutated), runs the named test file(s) on the
// mirror, expects RED, restores the copy. (The M1 review's F1–F8 items plus
// the M2 front-end and fix-round mutations, re-run as a script so the proof is
// repeatable.) A mutation whose site is not found exactly once is NOT RUN.
//
// THE GATE: the script exits NON-ZERO if any mutation is NOT RUN (its site
// moved — the proof silently shrank) or GREEN (the tests do not bite), or if
// the unmutated suite fails on the mirror. It exits 0 only when every
// mutation ran and went RED.
//
// usage: bun compiler/self-host-v2/slice-m1/bench/mutations.js
//        MUTATIONS_PROOF=absent   — run ONE synthetic mutation whose site does not exist (must exit ≠ 0)
//        MUTATIONS_PROOF=harmless — run ONE synthetic mutation that edits only a comment (GREEN; must exit ≠ 0)

import { cpSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const ROOT = join(import.meta.dir, "..", "..", "..", "..");
const SH = "compiler/self-host-v2";
const T = (f) => `./${SH}/slice-m1/${f}`;
const T2 = (f) => `./${SH}/slice-m2/${f}`;
const T4 = (f) => `./${SH}/slice-m4/${f}`;
const RT = `${SH}/slice-m1/runtime/runtime.js`;

// The M3 typer mutations all edit analyze.scrml and are judged by the two
// typer suites: [id, from, to] triples.
// A 4th element names another bootstrap file (default analyze.scrml).
// (s442: the S440-ruled suite typer-s440.test.js judges them too.)
const TYPER = (rows) => rows.map(([id, from, to, file]) => ({
  id, file: `${SH}/${file ?? "analyze.scrml"}`, from, to, tests: [T2("typer-gap.test.js"), T2("typer.test.js"), T2("typer-s440.test.js")],
}));

const MUTATIONS = [
  { id: "F1 self-write no-op removed (throws inside a click handler)", file: RT,
    from: "  if (from === to) return;\n", to: "", tests: [T("dropdown.browser.test.js")] },
  { id: "F2 surviving row's item not updated", file: RT,
    from: "      old.row.item.set(item);\n", to: "", tests: [T("dropdown.browser.test.js")] },
  { id: "F3 disposed Derived stays subscribed", file: RT,
    from: "scope.own(() => { this.disposed = true; unsubscribe(this); stats.deriveds--; });",
    to: "scope.own(() => { this.disposed = true; stats.deriveds--; });",
    tests: [T("runtime.test.js"), T("dropdown.browser.test.js")] },
  { id: "F3 disposed scope stays in parent's children", file: RT,
    from: "    if (this.parent) this.parent.children.delete(this);\n", to: "",
    tests: [T("runtime.test.js"), T("dropdown.browser.test.js")] },
  { id: "F3 <each> renders rows while tracking", file: RT,
    from: "untrack(() => { rows = reconcile(scope, anchor, rows, items, key, render); });",
    to: "rows = reconcile(scope, anchor, rows, items, key, render);", tests: [T("runtime.test.js")] },
  { id: "F3 `let` initializer evaluated while tracking", file: RT,
    from: "  if (constructing === 0) return new Cell(untrack(init));",
    to: "  if (constructing === 0) return new Cell(init());", tests: [T("runtime.test.js")] },
  { id: "L12(b) instance creation deferred to mount (M1's behaviour)", file: `${SH}/print.scrml`,
    from: 'handles: hs, shared: [], rows: [], slot: jid("slot$"), prebuilt: true }',
    to: 'handles: hs, shared: [], rows: [], slot: jid("slot$"), prebuilt: false }',
    tests: [T("dropdown.browser.test.js")] },
  { id: "L12(b) shared instance registered only after its factory ran", file: RT,
    from: "    decl.shared = inst;\n    factory(inst);\n",
    to: "    factory(inst);\n    decl.shared = inst;\n",
    tests: [T("dropdown.browser.test.js")] },
  { id: "F3 handlers not batched", file: RT,
    from: "const h = (e) => batch(() => handler(e));", to: "const h = (e) => handler(e);",
    tests: [T("runtime.test.js")] },
  { id: "F3 rule= edge check never rejects", file: RT,
    from: "if (!allowed || !allowed.includes(to)) {", to: "if (false) {", tests: [T("runtime.test.js")] },
  { id: "F4 FieldAt always granted (the original hole)", file: `${SH}/check.scrml`,
    from: ".FieldAt(path: path) :> fieldAtProblem(p, f, path)", to: '.FieldAt(path: path) :> ""',
    tests: [T("check.test.js")] },
  { id: "F5 C4 instance/declaration mismatch not reported", file: `${SH}/check.scrml`,
    from: "            if (target.sym.id != d.sym.id) {\n                out = out.concat([\"C4:",
    to: "            if (false) {\n                out = out.concat([\"C4:", tests: [T("check.test.js")] },
  { id: "F7 Static transition accepted without proof", file: `${SH}/check.scrml`,
    from: "            if (reachableFromEveryState(g, n, to)) return \"\"", to: "            return \"\"",
    tests: [T("check.test.js")] },
  // ---- slice M2: one per front-end phase (the equality proof or the source-level suite goes RED) ----
  { id: "M2 parse: markup children that are elements are dropped", file: `${SH}/parse.scrml`,
    from: "                out = out.concat([rn.n])\n", to: "",
    tests: [T2("lower.test.js")] },
  { id: "M2 analyze: `@x` of a program field resolved to the shared instance everywhere (L1 broken)", file: `${SH}/analyze.scrml`,
    from: "        if (inProgramCtx(env)) return InstRef.Lexical(0)\n", to: "",
    tests: [T2("lower.test.js")] },
  { id: "M2 analyze: `<*x/>` mis-resolved (every reference taken as predefined)", file: `${SH}/analyze.scrml`,
    from: "        const d: DeclSrc | not = declNamed(env.g, e.tag)\n        if (d is not) {",
    to: "        const d: DeclSrc | not = not\n        if (d is not) {",
    tests: [T2("front.test.js")] },
  { id: "M2 lower: a field's edit grants dropped (a graph field loses its Transition grant)", file: `${SH}/lower.scrml`,
    from: "            grants: f.grants, graph: f.graph, exported: f.exported, wcap: f.wcap,",
    to: "            grants: { replace: f.grants.replace, edits: [] }, graph: f.graph, exported: f.exported, wcap: f.wcap,",
    tests: [T2("lower.test.js")] },
  { id: "M2 lower: L7 ternary arms swapped", file: `${SH}/lower.scrml`,
    from: "        return Expr.Match(test, [tArm, fArm])", to: "        return Expr.Match(test, [fArm, tArm])",
    tests: [T2("lower.test.js")] },
  { id: "M2 analyze: the spread shape treated as a genuine replace (O58 (b) hole reopened)", file: `${SH}/analyze.scrml`,
    from: "        if (p.path.length == 0 && isSelfSpread(target, value)) return resolveSpread(env, e, p, f, value, st)\n", to: "",
    tests: [T2("front.test.js")] },
  { id: "F-B lower: reset of a user declaration's field inlines the DECLARED initializer (ignores the use-site value)", file: `${SH}/lower.scrml`,
    from: "        if (!isProgramKind(di.kind)) return [Stmt.Write(w.cap, target, w.edit, Expr.InitOf(d, target, idx), w.check)]\n", to: "",
    tests: [T2("front.test.js")] },
  { id: "S437 reads require narrowing: an un-narrowed read through a `T | not` handle accepted", file: `${SH}/analyze.scrml`,
    from: "        if (!r.x.maybe) return r\n", to: "        return r\n",
    tests: [T2("front.test.js")] },
  // ---- S440: #1109 review fixes re-landed + spread writes all-or-nothing ----
  { id: "S440 F1: a spread override's value read AFTER the earlier writes (no snapshot local)", file: `${SH}/lower.scrml`,
    from: "                writes = writes.concat([Stmt.Write(w.cap, one, w.edit, Expr.Local(t), w.check)])",
    to: "                writes = writes.concat([Stmt.Write(w.cap, one, w.edit, lowerExpr(c, ps[sw.prop].value), w.check)])",
    tests: [T2("front.test.js")] },
  { id: "S440 F-A: the Commit's writes not batched (observers flush between writes outside a handler)", file: `${SH}/print.scrml`,
    from: "        return checks.concat([sexpr(rtCall(ctx, \"batch\", [JsExpr.JArrow([], writes)]))])\n", to: "        return checks.concat(writes)\n",
    tests: [T2("front.test.js")] },
  { id: "S440 ruling: STRICT SNAPSHOT off (override values read the live `@x`)", file: `${SH}/lower.scrml`,
    from: "        const sc: LC = { t: c.t, file: c.file, subst: c.subst, snap: snapOf(operand, snap, fields) }\n",
    to: "        const sc: LC = { t: c.t, file: c.file, subst: c.subst, snap: not }\n",
    tests: [T2("front.test.js")] },
  { id: "S440 N1: the spread snapshot is the WHOLE instance again (every field read → rt.snapshot, widened tracking)", file: `${SH}/lower.scrml`,
    from: "                const f: SnapField | not = snapFieldOf(s.fields, rest[0])\n",
    to: "                const f: SnapField | not = not\n",
    tests: [T2("front.test.js")] },
  { id: "S440 ruling: a duplicate spread-override key accepted (E-STRUCT-DUPLICATE-KEY off for the spread shape)", file: `${SH}/analyze.scrml`,
    from: "            if (ps[k].name == ps[j].name) return true\n", to: "            if (false) return true\n",
    tests: [T2("front.test.js")] },
  { id: "S440 F-A: the Commit re-resolves the instance per write (no `Let inst = Handle(…)`)", file: `${SH}/lower.scrml`,
    from: "        const one: InstRef = InstRef.Narrowed(inst)\n        let lets: Stmt[] = [Stmt.Let(inst, Expr.Handle(instOf(c, ws[0].w.inst)))]\n",
    to: "        const one: InstRef = instOf(c, ws[0].w.inst)\n        let lets: Stmt[] = []\n",
    tests: [T2("front.test.js")] },
  { id: "S440 F2: `@h` not narrowed inside its own `given` (E-DECL-HANDLE-NOT-NARROWED again)", file: `${SH}/analyze.scrml`,
    from: "        if (hn != \"\") inner = withNarrow(inner,", to: "        if (false) inner = withNarrow(inner,",
    tests: [T2("front.test.js")] },
  { id: "S440 all-or-nothing: the printed commit writes BEFORE it checks the edges", file: `${SH}/print.scrml`,
    from: "        return checks.concat([sexpr(rtCall(ctx, \"batch\", [JsExpr.JArrow([], writes)]))])\n",
    to: "        return [sexpr(rtCall(ctx, \"batch\", [JsExpr.JArrow([], writes)]))].concat(checks)\n",
    tests: [T2("front.test.js")] },
  { id: "S440 all-or-nothing: lower emits the spread's writes ungrouped (no Commit)", file: `${SH}/lower.scrml`,
    from: "        return lets.concat([Stmt.Commit(writes)])\n", to: "        return lets.concat(writes)\n",
    tests: [T2("front.test.js")] },
  { id: "S440 all-or-nothing: the commit's edge check skipped (an off-graph override is written silently)", file: `${SH}/print.scrml`,
    from: "        if (!isTransitionEdit(edit) || !isRuntimeEdge(check)) return []\n", to: "        return []\n",
    tests: [T2("front.test.js")] },
  { id: "S440 C7: a Commit write storing a non-Local accepted", file: `${SH}/check.scrml`,
    from: "            .Lit(lit: x) :> \"a Commit write's value is not a Local (the snapshot)\"", to: "            .Lit(lit: x) :> \"\"",
    tests: [T2("front.test.js")] },
  // ---- M3 item 1: the typer and the scope pass — one per check family, plus the
  // REVERSE mutations for the shapes the SPEC makes legal (a "stays silent" test
  // must go RED when the typer starts rejecting what the SPEC accepts) ----
  ...TYPER([
    ["M3 typer: a write's value never checked (§66.1 rule 5 off)",
     "        if (fitsType(x, target) != Verdict.Fails) return ts\n", "        return ts\n"],
    ["M3 typer: `not` into a non-optional type accepted (E-TYPE-041 off)",
     "        if (maybeInner(target) is some) return ts\n        return report(ts, env, span, \"E-TYPE-041\"",
     "        return ts\n        return report(ts, env, span, \"E-TYPE-041\""],
    ["M3 typer: call arity never checked",
     "        if (n >= 0 && n != args.length) {", "        if (false) {"],
    ["M3 typer: `<each in=…>` over a non-sequence accepted",
     "        if (kindOf(s) == 5) return ts\n", "        return ts\n"],
    ["M3 typer: use-site construction values never checked (§66.9 rule 8 / §7.5.1 position 2)",
     "                if (f.annotated && f.trusted) {\n                    const what: string", "                if (false) {\n                    const what: string"],
    ["M3 typer: a declaration's own initializer never checked (§7.5.1 position 2)",
     "            if (f.annotated && f.trusted) {\n                const lk: int = attrLiteralKind(f.init)", "            if (false) {\n                const lk: int = attrLiteralKind(f.init)"],
    ["S442 #9: `int` unenforced again (number → int unproven, S439 behaviour)",
     "            if (vk == 0) return Verdict.Fits\n            return Verdict.Fails\n",
     "            if (vk == 0) return Verdict.Fits\n            if (vk == 1) return Verdict.Unproven\n            return Verdict.Fails\n"],
    ["S442 #8 Q2: `a || b` typed from its operands again (JS operand semantics, S439)",
     "            .Or :> known(Type.Bool)", "            .Or :> VType.Unknown"],
    // (s442 r6: the S439 REVERSE row "a `T | not` value into a `T` position treated as provably wrong" is RETIRED —
    // S442 ruled exactly that ("`T | not` into `T` is an error for all types"); the rule now lives in mayBeNot, pinned
    // by the r6 rows below.)
    ["M3 typer: the Typing table not recorded (no type per expression node)",
     "        return rvt(r.vt, record(r.ts, e.nid, r.vt))\n", "        return rvt(r.vt, r.ts)\n"],
    // (S442: the two S439 REVERSE rows "a ternary test / an `if=` checked as `bool`" are retired —
    // S440 #4 = (c) RULED conditions checked; their replacements are the S442 rows below.)
    ["M3 REVERSE: a call's first argument checked against `int` (§7.5.1 position 3 \"SHALL compile\")",
     "        const ret: Type | not = fi.ret\n",
     "        if (args.length > 0) ts = checkValue(env, exprType0(ts, args[0].nid), Type.Int, e.span, \"an argument\", ts)\n        const ret: Type | not = fi.ret\n"],
    ["M3 scope: duplicate program cells accepted (E-SCOPE-010 off)",
     "                if (i >= 0) {\n                    const f: FieldInfo = d.fields[j]", "                if (false) {\n                    const f: FieldInfo = d.fields[j]"],
    ["M3 scope: duplicate file-scope functions accepted",
     "            if (i >= 0) {\n                const f: FnInfo = t.fns[j]", "            if (false) {\n                const f: FnInfo = t.fns[j]"],
    ["M3 scope: the §7.3.3 function-block rule off (E-SCOPE-REDECLARE)",
     "                out = out.concat(blockRedeclares(f.path, af.body, af.params, true))\n", ""],
    ["M3 scope: inline handler blocks not checked",
     "            out = out.concat(handlerRedeclares(f.path, fileMarkup(f.items)))\n", ""],
    ["M3 REVERSE: nested blocks inherit the parameters (shadowing wrongly refused)",
     "            for (const nb of nestedBlocks(s)) { out = out.concat(blockRedeclares(file, nb, [], inFn)) }",
     "            for (const nb of nestedBlocks(s)) { out = out.concat(blockRedeclares(file, nb, params, inFn)) }"],
    ["M3 scope: two `as=` of one name in one scope accepted",
     "                if (dup is not && o.owner == h.owner && o.name == h.name) dup = o\n", "                if (false) dup = o\n"],
    ["M3 scope: a program cell named like a declaration accepted",
     "                } else if (d.sym.id == t.program.id && visibleDeclNamed(files, t, d.file, names[j])) {", "                } else if (false) {"],
    ["M3 scope: a handle named like a program cell accepted",
     "            } else if (h.file == progFile && cells.indexOf(h.name) >= 0) {", "            } else if (false) {"],
    // ---- fix round 1 ----
    ["FR1-A: a local's reassignments not joined into its type (typed from the initializer only)",
     "                    ts1 = contribute(ts1, ls, r.vt)\n", ""],
    ["FR1-A: a local's annotation ignored (typed from its initializer)",
     "            return keepTEnv(tWithLocal(env, sym, known(annot)), ts2)", "            return keepTEnv(tWithLocal(env, sym, r.vt), ts2)"],
    ["FR1-B: a whole-struct literal's fields not checked",
     "checkNotElems(env, value, target, checkLitFields(env, value, checkValue(env, v, target, value.span, what, ts)))", "checkNotElems(env, value, target, checkValue(env, v, target, value.span, what, ts))"],
    ["FR1-C: a parse-recovery node typed as the `not` literal",
     ".Recovered :> rvt(VType.Unknown, ts)", ".Recovered :> rvt(VType.Absent, ts)"],
    ["FR1-C: a write into a field whose declaration failed to parse still checked",
     "        if (!f.trusted) return ts\n", ""],
    ["FR1-C: arity checked against a signature that did not parse",
     "                if (!paramsTrusted(f.errs, af.params)) arity = -1\n", ""],
    ["FR1-D: every declaration in the link set claims `@name` (not only the visible ones)",
     "                if (d.file == file || importsName(files, file, name)) return true", "                return true"],
    ["FR1-G1: `<each in=not>` accepted",
     "        if (isAbsentVT(v)) {\n            return report(", "        if (false) {\n            return report("],
    ["FR1-F1: a duplicate type name in one file accepted",
     "                if (first.file == ti.file) {\n                    out = out.concat([mkDiag(ti.file, ti.span, \"E-BOOTSTRAP-REDECLARE\"",
     "                if (false) {\n                    out = out.concat([mkDiag(ti.file, ti.span, \"E-BOOTSTRAP-REDECLARE\""],
    ["FR2-1: a program cell visible from every file (§7.6.1 'in the same file' dropped)",
     "        if (d.file != env.file) return not\n", ""],
    ["FR2-1: `@x` reaches a declaration the file neither declares nor imports",
     "        if (d.file == env.file || importsName(env.g.files, env.file, name)) return d\n        return not", "        return d"],
    ["FR2-2: a row / renders handle may shadow a visible cell (PA interim: refuse)",
     "            } else if (h.file == progFile && cells.indexOf(h.name) >= 0) {", "            } else if (h.owner == progNid && cells.indexOf(h.name) >= 0) {"],
    ["FR2-3: `key=` resolved in the row env (sees the row's own handles)",
     "                st = resolveValue(kenv, a.value, not, st)", "                st = resolveValue(renv, a.value, not, st)"],
    ["FR2-4: an annotated local's literal initializer not checked (§7.5.1 position 1)",
     "            let ts2: TypeState = checkInit(env, annot, literalKind(init), init.span, \"`\" + name + \"`\", r.ts)", "            let ts2: TypeState = r.ts"],
    ["FR2-4: a write to an annotated local not checked",
     "                    ts1 = checkLitFields(env, value, checkValue(env, r.vt, la, value.span, placeLabel(target), ts1))", "                    ts1 = ts1"],
    ["FR2-5: a field's trust judged by an error ANYWHERE in its declaration (coarse Rule C)",
     // s444: re-pointed after r8 (trustFields now ANDs the binder's `f.trusted`); same corruption, r8's AND kept
     "            out = out.concat([{ nid: f.nid, span: f.span, annotated: f.annotated, trusted: f.trusted && typeTrusted(errs, f.typeSpan),",
     "            out = out.concat([{ nid: f.nid, span: f.span, annotated: f.annotated, trusted: f.trusted && !hasErrIn(errs, f.span),"],
    ["FR2-5: an opener type's span stops before its unreadable continuation (`int|not` trusted as `int`)",
     "        if (end > m.pos) ty = { nid: ty.nid, span: mkSpan(start, end), k: ty.k }\n", "", "parse.scrml"],
    ["FR2-7: the fixpoint bound fixed at 6 passes (a chain of 6 locals goes Unknown)",
     "            if (pass == 0) bound = 3 * next.length + 2", "            if (pass == 0) bound = 6"],
    ["FR2-8: compound assignment recovered as a typed `x = v`",
     "            return mkE(rhs2.tp, start, AExprK.Recovered)", "            return mkE(rhs2.tp, start, AExprK.Assign(lhs.e, rhs2.e))", "parse.scrml"],
    ["R3-H1: a field write through an annotated local checked against the WHOLE annotation",
     "                if (la is some && bareLocal) {", "                if (la is some) {"],
    ["R3-H1: a field write through an unannotated local joined into the local's type",
     "                } else if (la is not && bareLocal) {", "                } else if (la is not) {"],
    ["FR1-F2: duplicate parameter names accepted",
     "                out = out.concat([mkDiag(file, ps[j].span, \"E-BOOTSTRAP-REDECLARE\"", "                if (false) out = out.concat([mkDiag(file, ps[j].span, \"E-BOOTSTRAP-REDECLARE\""],
    // ---- s442: the S440-ruled checks (docs/changes/s442-bootstrap-typer-rules/) ----
    ["S442 #3: `S | not` over a NON-sequence admitted (only the outer `| not` looked at)",
     "        if (inner is some) s = inner", "        if (inner is some) return ts"],
    ["S442 dup keys: a repeated key in a plain / nested struct literal accepted",
     "            if (!ps[j].spread && keyBefore(ps, j)) st = dupOverride(env, st, ps[j])", "            if (false) st = dupOverride(env, st, ps[j])"],
    ["S442 #7: conditions never checked (truthiness back)",
     "            .Known(t: t) :> condKnown(env, c, t, what, ts)", "            .Known(t: t) :> ts"],
    ["S442 #7 Q1 REVERSE: a `T | not` condition refused (presence test lost)",
     "            }\n            return markPresence(ts, c.nid)\n", "            }\n            return report(ts, env, c.span, \"E-COND-NOT-BOOLEAN\", \"x\")\n"],
    ["S442 #7 Q1: a presence test not lowered (`if=@o.n` over `0` is JS-falsy again)",
     "        if (presenceTest(c.t, e.nid)) return Expr.Prim(PrimOp.IsSome, [presenceOperand(c, e)])\n", "", "lower.scrml"],
    ["S442 #8: arithmetic / relational operands never checked",
     "            .Known(t: t) :> numKnown(env, x, t, what, ts)", "            .Known(t: t) :> ts"],
    ["S442 #8: `string + number` accepted (the `+` pair rule off)",
     "        if (kindOf(x) == 2 && kindOf(y) == 2) return ts\n", "        return ts\n"],
    ["S442 #8 Q2: `!` / `&&` / `||` operands never checked",
     "            .Known(t: t) :> boolKnown(env, x, t, what, ts)", "            .Known(t: t) :> ts"],
    ["S442 #8 Q3 REVERSE: narrowing ignored (a narrowed `T | not` read stays `T | not`)",
     "        if (key != \"\" && env.narrowed.indexOf(key) >= 0) return known(inner)\n", ""],
    ["S442 #8 Q3 REVERSE: no narrowing after an early `return`",
     "        if (aExits && !bExits) return withNarrowed(env, b.narrowed)\n", ""],
    ["S442 #8 Q3 REVERSE: the right operand of `&&` not narrowed by the left",
     "        if (isAnd) renv = tCallUnnarrow(tNarrow(env, condNarrowing(env, l).yes), l)   // r3 N1: what the left operand's calls write is not narrowed\n", ""],
    ["S442 #8 Q3: a write of a narrowed place does not un-narrow it",
     "        const out: TEnv = tUnnarrow(tCallUnnarrow(env, e), key)\n", "        const out: TEnv = tCallUnnarrow(env, e)\n"],
    ["S442 r2 F1a: a call never drops a narrowing (callee write sets ignored)",
     "                    if (k.indexOf(\"@\") == 0) out = tUnnarrow(out, k)\n", ""],
    ["S442 r2 F1a: write sets not closed over calls (a callee's callee ignored)",
     "                            if (keys.indexOf(c) < 0) {\n                                keys = keys.concat([c])\n                                changed = true\n                            }\n",
     ""],
    ["S442 r2 F1b: an `if` leaves the THEN path's narrowing (no join)",
     "        return withNarrowed(env, both)\n", "        return withNarrowed(env, a.narrowed)\n"],
    ["S442 r2 F1b: a bare local write never un-narrows the local",
     "            if (s is some) return \"#\" + s.id\n", ""],
    ["S442 r2 F3: a write of a present value does not narrow",
     "        if (key != \"\" && writesPresent(e, ts)) return keepTEnv(tNarrow(out, [key]), ts)\n", ""],
    ["S442 r2 F3 REVERSE: a write of a `T | not` value narrows too",
     "        return maybeInner(x) is not\n    }", "        return true\n    }"],
    // (s442 r2: the joined-local carve-out and its two rows are retired — see progress.md r2 follow-through)
    ["S442 r2 follow-through: a `T | not` operand never reported (Q3 off)",
     "        return report(ts, env, x.span, \"E-OPERAND-NOT-NARROWED\"", "        return ts\n        return report(ts, env, x.span, \"E-OPERAND-NOT-NARROWED\""],
    ["S442 #8 REVERSE: Rule C off for operators (checked across a parse error)",
     "        if (hasErrIn(env.errs, e.span)) return ts\n        return match op {", "        return match op {"],
    ["S442 #9: `/` on two ints accepted (E-INT-DIVISION off)",
     "            if (kindOf(unMaybe(x)) == 0 && kindOf(unMaybe(y)) == 0) {", "            if (false) {"],
    ["S442 #9: the `int` initializer rule off (§7.5.1 not widened to `int`)",
     "        if (tk == 0) {\n            if (lk == 4) return 1\n            return 0\n        }\n", "        if (tk == 0) {\n            return -1\n        }\n"],
    ["S442 r2 F4: a hex literal classified by its digits (`0xE` typed `number`)",
     "        if (isRadixLiteral(raw)) return Type.Int\n", ""],
    ["S442 r3 N1: `&&`'s right operand narrowed across the left operand's writing call",
     "        if (isAnd) renv = tCallUnnarrow(tNarrow(env, condNarrowing(env, l).yes), l)", "        if (isAnd) renv = tNarrow(env, condNarrowing(env, l).yes)"],
    ["S442 r3 N1: `||`'s right operand narrowed across the left operand's writing call",
     "        if (isOr) renv = tCallUnnarrow(tNarrow(env, condNarrowing(env, l).no), l)", "        if (isOr) renv = tNarrow(env, condNarrowing(env, l).no)"],
    ["S442 r4 (c) / r7 A: returns never checked (any type)",
     "        // r7 A: full assignability for EVERY return type (§7.5.1 position 4)\n        return checkValue(", "        return ts1\n        return checkValue("],
    ["S442 r4 (c) / r7 A: arguments never checked (any type)",
     "        if (n >= 0 && n == args.length) ts = checkArgs(env, fi.name, args, ts)\n", ""],
    ["S442 r4 (c): non-literal initializers not checked against an `int` annotation",
     "        if (!hasInt(target)) return checkMaybeNot(env, v, target, span, what, ts)\n        return checkValue(env, v, target, span, what, ts)", "        if (!hasInt(target)) return checkMaybeNot(env, v, target, span, what, ts)\n        return ts\n        return checkValue(env, v, target, span, what, ts)"],
    ["S442 r7 A: arguments back to `int`-only (the pre-A boundary)",
     "                ts = checkValue(env, exprType0(ts, args[i].nid), pt, args[i].span, what, ts)", "                if (hasInt(pt)) ts = checkValue(env, exprType0(ts, args[i].nid), pt, args[i].span, what, ts)"],
    ["S442 r4 (c): struct literals in a declaration / use-site initializer not checked field by field",
     "        return checkNotElems(env, x, target, checkLitFields(env, x, ts))", "        return checkNotElems(env, x, target, ts)"],
    ["S442 r4 (b): a presence test of a conditional handle does not narrow (S437 read error inside)",
     "            const maybe: boolean = h.conditional && env.present.indexOf(name) < 0", "            const maybe: boolean = h.conditional"],
    ["S442 r4 (b): a handle presence test lowered as a snapshot read (crashes while unmounted)",
     "        if (i is some) return Expr.Handle(instOf(c, i))\n", "", "lower.scrml"],
    ["S442 r4 (f) REVERSE: a markup `${x}` of a `T | not` treated as an un-narrowed operand",
     "        return r.ts                                         // (f): a `T | not` renders nothing — silent",
     "        return notNarrowed(env, x, t, \"`${}`\", r.ts)"],
    ["S442 r4 (d): a handle named like a visible declaration accepted",
     "            } else if (visibleDeclNamed(files, t, h.file, h.name)) {", "            } else if (false) {"],
    ["S442 r5 R5: a ROW / renders handle named like a visible declaration accepted (program scope only)",
     "            } else if (visibleDeclNamed(files, t, h.file, h.name)) {", "            } else if (h.owner == progNid && visibleDeclNamed(files, t, h.file, h.name)) {"],
    ["S442 r4 (a): a bare `bool | not` condition taken as a presence test again",
     "            if (kindOf(inner) == 3) {\n                return report(", "            if (false) {\n                return report("],
    ["S442 r3 N3: a write of an `<each>` source keeps the row binding's narrowing",
     "            if (r.key != \"\" && (underAny(r.key, drop) || underAny(key, [r.key]))) drop", "            if (false) drop"],
    ["S442 r6: an un-narrowed `T | not` into `T` accepted (any type)",
     "        if (mayBeNot(x, target)) {\n            return report(", "        if (false) {\n            return report("],
    ["S442 r6: the `T | not` rule back to `int` targets only (the r5 scope)",
     "        if (mayBeNot(x, target)) {\n            return report(", "        if (mayBeNot(x, target) && hasInt(target)) {\n            return report("],
    ["S442 r6: a sequence element that may be `not` accepted (only the outer type looked at)",
     "        if (xe is some && te is some) return mayBeNot(xe, te)\n", ""],
    ["S442 r6 REVERSE: `T | not` into `T | not` refused",
     "            if (ti is some) return mayBeNot(xi, ti)\n", ""],
    ["S442 r7 N2: a `T | not` element type printed unparenthesized (`int | not[]`)",
     "        if (maybeInner(e) is some) return \"(\" + typeName(e) + \")\"\n", ""],
    ["S442 r7 C: a provably-`not` NON-literal initializer of a non-int type accepted (returns / arguments are checkValue's since A)",
     "        if (isAbsentVT(v)) return checkAbsent(env, target, span, what, ts)\n", ""],
    ["S442 r7 C: `not` elements of an untyped array literal accepted",
     "                out = checkAbsent(env, te, x.span, \"an element of `\" + typeName(target) + \"`\", out)", "                out = out"],
    ["S442 r7 C REVERSE: `not` elements checked in a TYPED array too (double report with E-TYPE-031)",
     "        if (knownOf(exprType0(ts, e.nid)) is some) return ts\n", ""],
    ["S442 r7 A guard (i): an unresolved return type (E-TYPE-UNKNOWN placeholder) trusted",
     "                        if (!rt.unresolved) ret = rt.t\n", "                        ret = rt.t\n"],
    ["S442 r8 F1: an unresolved PARAMETER type trusted at the call (argument checked against the placeholder)",
     "            if (env.t.unresolved.params.indexOf(pnids[i]) >= 0) pt = not      // r8: an unresolved parameter type\n", ""],
    ["S442 r8 F1: an unresolved PARAMETER type trusted inside the body",
     "            if (paramsTrusted(env.errs, [p]) && env.t.unresolved.params.indexOf(p.nid) < 0) pvt = paramType(pf)", "            if (paramsTrusted(env.errs, [p])) pvt = paramType(pf)"],
    ["S442 r8 F1: an unresolved PARAMETER type never recorded",
     "                        if (unresolved) st = badParam(st, p.nid)     // r8: never checked against\n", ""],
    ["S442 r8 F1: an unresolved struct FIELD type checked in a struct literal",
     "                    if (fd.sym.hint == p.name && env.t.unresolved.fields.indexOf(fd.sym.id) < 0) {", "                    if (fd.sym.hint == p.name) {"],
    ["S442 r8 F1: an unresolved struct FIELD type never recorded",
     "            if (unresolved) st = badField(st, fsym.id)     // r8: never checked against\n", ""],
    ["S442 r8 F1: an unresolved DECLARATION field type trusted",
     "            resolved = !rt.unresolved     // r8: an unknown type name → untrusted\n", ""],
    ["S442 r8 F1: an unresolved LOCAL annotation taken as the local's type",
     "            if (!rt.unresolved) annot = rt.t\n", "            annot = rt.t\n"],
    // s444 review fix round (typer-s440.test.js "S444 R1" / "S444 R2")
    ["S444 R1: a READ of an unresolved declaration cell typed by the placeholder (fieldTypeOf ignores trusted)",
     "        if (!di.fields[idx].trusted) return VType.Unknown\n", ""],
    ["S444 R2: a GRANT error makes the type unresolved (coarse predicate — the independent mismatch hidden)",
     "positionsWritable: writable }), st: st, unresolved: re.unresolved }", "positionsWritable: writable }), st: st, unresolved: re.unresolved || st.diags.length > st0.diags.length }"],
    ["S444 R2: an unknown type NAME not marked unresolved (the placeholder checked against)",
     "\"unknown type `\" + n + \"`\"), unresolved: true }", "\"unknown type `\" + n + \"`\"), unresolved: false }"],
    ["S444 R2: `T | not` drops its inner type's unresolved mark",
     "        return { t: Type.Maybe(r.t), st: r.st, unresolved: r.unresolved }", "        return { t: Type.Maybe(r.t), st: r.st, unresolved: false }"],
    ["S444 R2: `T[…]` drops its element type's unresolved mark",
     "positionsWritable: writable }), st: st, unresolved: re.unresolved }", "positionsWritable: writable }), st: st, unresolved: false }"],
    ["S442 r7 A guard (ii): a callee declared in two files trusted (mis-link cascades)",
     "        if (inManyFiles(env.t, fi.name)) return rvt(VType.Unknown, ts)\n", ""],
    ["S442 r7 B: an optional-sequence target's elements not checked (`[@o.n]` into `int[] | not` accepted)",
     "        if (ti is some) return mayBeNot(x, ti)\n", ""],
    ["S442 r6: a non-int return / argument / initializer not checked for the `T | not` rule",
     "        if (!mayBeNot(x, target)) return ts\n        return checkKnown(", "        return ts\n        return checkKnown("],
    ["S442 r7 A: returns back to `int`-only (the pre-A boundary)",
     "        // r7 A: full assignability for EVERY return type (§7.5.1 position 4)\n        return checkValue(", "        if (!hasInt(rt)) return ts1\n        return checkValue("],
    ["S442 r5 R3: a repeated conditional-handle presence test inside its narrowing refused",
     "        if (isCondHandle(env, c)) return markPresence(ts, c.nid)\n", ""],
    ["S442 r5 R1: a nested row whose source lies under a dropped row keeps its narrowing (one level only)",
     "(underAny(r.key, drop) || underAny(key, [r.key]))",
     "(underAny(r.key, [key]) || underAny(key, [r.key]))"],
    ["S442 r3 N3: the row binding never tied to its source",
     "        if (bind is some) renv = tWithRow(tWithLocal(env, bind, elem), bind, eachSourceKey(env, e))", "        if (bind is some) renv = tWithLocal(env, bind, elem)"],
    // ---- s442 fix round r1 (review F1 / F2 / F3) ----
    ["S442 r1 F1: `a && b` typed from its operands again (the `&&` arm of Q2)",
     "            .And :> known(Type.Bool)", "            .And :> VType.Unknown"],
    ["S442 r1 F2 REVERSE: Rule C off for conditions (judged across a parse error)",
     "        if (hasErrIn(env.errs, c.span)) return ts          // Rule C: not judged across a parse error\n", ""],
    ["S442 r1 F3: E-INT-DIVISION reported on top of the operand reports (the single-report guard off)",
     "        const ts: TypeState = checkNumPair(env, e, l, r, a, b, \"`/`\", ts0)\n        if (ts.diags.length > ts0.diags.length) return ts\n",
     "        const ts: TypeState = checkNumPair(env, e, l, r, a, b, \"`/`\", ts0)\n"],
    ["S442 #7: a conditional handle typed `T` (its `| not` lost — `if=@color` refused)",
     "            if (h.sym.id == s.id && h.conditional) return Type.Maybe(Type.Named(d))", "            if (false) return Type.Maybe(Type.Named(d))"],
    ["S442 #4 (ruling #5 (ii)): a handle named like a cell accepted in a ROW (only the program scope refused)",
     "            } else if (h.file == progFile && cells.indexOf(h.name) >= 0) {", "            } else if (h.owner == progNid && h.file == progFile && cells.indexOf(h.name) >= 0) {"],
  ]),
  // ---- M3 item 2: the tables split by fact family, indexed by NodeId ----
  { id: "M3 tables: the index build skips each table's first fact", file: `${SH}/analyze.scrml`,
    from: "        while (i >= 0) {\n            // backwards: a node's first entry is written last, and stays",
    to: "        while (i > 0) {\n            // backwards: a node's first entry is written last, and stays",
    tests: [T2("tables.test.js")] },
  { id: "M3 tables: the index's empty slot is 0, not -1 (every node without a fact answers the first fact)", file: `${SH}/analyze.scrml`,
    from: "        if (n <= 0) return []\n        let out: int[] = [-1]", to: "        if (n <= 0) return []\n        let out: int[] = [0]",
    tests: [T2("tables.test.js")] },
  { id: "M3 tables: a node's fact answered by the wrong family (a `given` recorded as a name)", file: `${SH}/analyze.scrml`,
    from: "        st = addBind(rs.st, s.nid, BindFact.BGiven(rs.s, inst))",
    to: "        st = addName(rs.st, s.nid, NameFact.NLocal(rs.s))",
    tests: [T2("tables.test.js")] },
  { id: "M3 tables: exprType's index points one entry off", file: `${SH}/analyze.scrml`,
    from: "            if (exprs[i].nid >= 0) at[exprs[i].nid] = i\n", to: "            if (exprs[i].nid >= 0) at[exprs[i].nid] = i + 1\n",
    tests: [T2("tables.test.js")] },
  { id: "M3 tables: every expression typed twice (a duplicate typing entry per node)", file: `${SH}/analyze.scrml`,
    from: "        return rvt(r.vt, record(r.ts, e.nid, r.vt))\n", to: "        return rvt(r.vt, record(record(r.ts, e.nid, r.vt), e.nid, r.vt))\n",
    tests: [T2("tables.test.js")] },
  { id: "M3 tables: a row value `@.` recorded twice in the names family", file: `${SH}/analyze.scrml`,
    from: "        return plain(row.ty, addName(st, e.nid, NameFact.NLocal(row.bind)))",
    to: "        return plain(row.ty, addName(addName(st, e.nid, NameFact.NLocal(row.bind)), e.nid, NameFact.NLocal(row.bind)))",
    tests: [T2("tables.test.js")] },
  // ---- s442: the §66.19 six-programs front end — its DIAGNOSTICS (codes-only; the runtime constructs are
  // certified by the bite matrix's front section, slice-m3/bench/bite-matrix.js --front) ----
  { id: "s442: `single` inside a multi-instance declaration accepted (E-COMPONENT-ENGINE-SCOPE never fires)", file: `${SH}/analyze.scrml`,
    from: "            if (hasFlag(c.mods, \"single\")) {", to: "            if (false) {", tests: [T4("engine.test.js")] },
  { id: "s442 r1 O55: a plain `<x/>` of a `single` program cell rendered as HTML (E-DECL-SINGLE-INSTANTIATED dropped)", file: `${SH}/analyze.scrml`,
    from: "        if (sd is some) return singleInstantiated(env, e, st)", to: "", tests: [T4("engine.test.js")] },
  { id: "s442 r1 O55/F2: a plain use of a `single` USER declaration makes a second instance", file: `${SH}/analyze.scrml`,
    from: "            if (d.info.single) return singleInstantiated(env, e, st)", to: "", tests: [T4("engine.test.js"), T4("review-r1.test.js")] },
  { id: "s442 r1 F1: a sequence shape on a LOCAL taken as a cell write (the statement is deleted)", file: `${SH}/analyze.scrml`,
    from: "        if (shape > 0 && !rootIsLocal(env, target)) return", to: "        if (shape > 0) return", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 F1: an edit call on a LOCAL taken as a cell edit (the statement is deleted)", file: `${SH}/analyze.scrml`,
    from: "            if (rootIsLocal(env, m.obj)) return localEditRefused(env, e, m.method, args, st)", to: "", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 F3: `>=` ends a `:`-shorthand body (the tail leaks as text)", file: `${SH}/lex.scrml`,
    from: "        if (c0 == 62) return peekCode(c, 1) != 61", to: "        if (c0 == 62) return true", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 F3: a bare `>` comparison in a shorthand accepted (its tail rendered as page text)", file: `${SH}/parse.scrml`,
    from: "            m = comparisonTail(m, start)\n", to: "", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 F4: a state-child body parsed as FREE text (quotes rendered, prose accepted)", file: `${SH}/parse.scrml`,
    from: "            const kids: RNodes = parseCodeBody(m, o.name)", to: "            const kids: RNodes = parseKids(m, o.name)", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 F5: a multi-element append shape interleaves evaluation and writes", file: `${SH}/lower.scrml`,
    from: "        const edit: Stmt = Stmt.Commit(writes)",
    to: "        if (!prepend) {\n            let direct: Stmt[] = []\n            for (const v of values) { direct = direct.concat([Stmt.Write(w.cap, target, w.edit, v, w.check)]) }\n            return direct\n        }\n        const edit: Stmt = Stmt.Commit(writes)", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 F6: a shape's elements evaluated RIGHT to left", file: `${SH}/lower.scrml`,
    from: "            lets = lets.concat([Stmt.Let(tmps[k], v)])", to: "            lets = [Stmt.Let(tmps[k], v)].concat(lets)", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 nit: a closer right after a shorthand body accepted", file: `${SH}/parse.scrml`,
    from: "        if (n == 0) return mp", to: "        return mp", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 nit: a duplicate state-child accepted", file: `${SH}/analyze.scrml`,
    from: "            if (origin >= 0 && seen.indexOf(origin) >= 0) {", to: "            if (false) {", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 nit: a sequence shape over a non-sequence not a type error", file: `${SH}/analyze.scrml`,
    from: "            if (seqElem(pty) is not) {", to: "            if (false) {", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 nit: `<*f/>` of another declaration's field called a predefined element", file: `${SH}/analyze.scrml`,
    from: "            if (owner != \"\") {", to: "            if (false) {", tests: [T4("review-r1.test.js")] },
  // (s444: the r1 G1 "constructs-nothing" row is RETIRED — `<*x/>` is a Core View.Star now and renders
  //  markup that constructs instances; its bite is the "s444 A3 … inlined again" row below)
  { id: "s442 r1 G1: `<*x/>` of a declaration inlined inside another declaration's renders", file: `${SH}/analyze.scrml`,
    from: "        if (!inProgramCtx(env)) {", to: "        if (false) {", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 G1: `<*x/>` of a declaration with no renders accepted (O51)", file: `${SH}/analyze.scrml`,
    from: "        if (nodes.length == 0) {", to: "        if (false) {", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 G1: an attribute on `<*f/>` of a field accepted", file: `${SH}/analyze.scrml`,
    from: "        if (e.attrs.length > 0) {\n            return addDiag(st, env.file, e.span, \"E-DECL-STAR-REF-ATTR-WRITE\"",
    to: "        if (false) {\n            return addDiag(st, env.file, e.span, \"E-DECL-STAR-REF-ATTR-WRITE\"", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 G2: an own value AND attributes accepted (O19 decided silently)", file: `${SH}/analyze.scrml`,
    from: "        if ((hasOwnValue(d.own) || hasOwnType(d)) && d.attrs.length > 0) {", to: "        if (false) {", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 G3: `<*x/>` of a declaration with a default-less attribute accepted (O33 → a runtime throw)", file: `${SH}/analyze.scrml`,
    from: "            if (isAttributeRole(f.role) && !hasOwnValue(f.init)) {", to: "            if (false) {", tests: [T4("review-r1.test.js")] },
  // (s444 Phase B: the s442 "validator flags accepted silently (the O25 refusal dropped)" row is RETIRED — O25 is
  //  RULED (dpa-058) and validators are parsed and honored; its bite is the "s444 B: a bare validator word … read as
  //  an opener modifier again" row)
  { id: "s442: an ungranted recognized sequence shape accepted as a grant", file: `${SH}/analyze.scrml`,
    from: "        let isGranted: boolean = f.grants.replace || hasEditKind(f.grants.edits, edit)\n",
    to: "        let isGranted: boolean = true\n", tests: [T4("audit.test.js"), T4("grants.test.js")] },
  { id: "s442: `.shift()` classified at the END (granted by `pop`)", file: `${SH}/analyze.scrml`,
    from: "        let place: SeqAt = SeqAt.Front\n",
    to: "        let place: SeqAt = SeqAt.End\n", tests: [T4("audit.test.js"), T4("grants.test.js")] },
  { id: "s442: an element-field write judged by the TAPE's grants instead of the field's (dpa-052 Q3)", file: `${SH}/analyze.scrml`,
    // (s444: re-sited — the element-field check now reads the target's contract twice: any contract, then `replace`)
    from: "        if (!target.grants.replace && target.grants.edits.length == 0) {",
    to: "        if (!f.grants.replace && f.grants.edits.length == 0) {", tests: [T4("audit.test.js")] },
  { id: "s442: a lambda parsed as its body alone (the `.filter(…)` shape never recognized)", file: `${SH}/parse.scrml`,
    from: "        return mkE(body.tp, start, AExprK.Lambda(params, body.e))", to: "        return body", tests: [T4("parse.test.js"), T4("audit.test.js")] },
  { id: "s442: the typer skips state-child bodies (Typing coverage)", file: `${SH}/analyze.scrml`,
    from: "                for (const sc of stateChildOf(c)) { ts = typeNodes(env, sc.body, ts) }",
    to: "                for (const sc of stateChildOf(c)) { ts = ts }", tests: [T4("typing.test.js")] },
  { id: "s442: the typer skips a child field's own renders (Typing coverage)", file: `${SH}/analyze.scrml`,
    // (s444: re-sited — the validator arguments are typed right after it)
    from: "            if (r is some) ts = typeElem(env, r, ts)\n            ts = typeValidatorArgs(",
    to: "            if (false) ts = typeElem(env, r, ts)\n            ts = typeValidatorArgs(", tests: [T4("typing.test.js")] },
  { id: "s442: a spread-append's elements not checked against the element type", file: `${SH}/analyze.scrml`,
    from: "            ts = checkWrite(env, ed.w, exprType0(ts, x.nid), x, \"an element of this sequence\", ts)",
    to: "            ts = ts", tests: [T4("typing.test.js"), T4("audit.test.js")] },
  { id: "s442: `<theme>` parsed as markup (its CSS refusal dropped — the tokens vanish silently)", file: `${SH}/parse.scrml`,
    from: "    fn isThemeOpener(o: Opener) -> boolean { return !o.star && o.name == \"theme\" }",
    to: "    fn isThemeOpener(o: Opener) -> boolean { return false }", tests: [T4("theme.test.js")] },
  { id: "s442: a named shared instance read as a field-less declaration (its refusal dropped)", file: `${SH}/analyze.scrml`,
    from: "                if (n != \"\" && declNames.indexOf(n) >= 0) {", to: "                if (false) {", tests: [T4("theme.test.js")] },
  // ---- s442: RULED S442 grow/shrink split (append/pop, prepend/shift, insert/remove; anywhere covers end/front) ----
  { id: "s442 grants: `insert` does not cover appends / prepends", file: `${SH}/analyze.scrml`,
    from: "        if (hasEditKind(out, EditKind.Anywhere)) {", to: "        if (false) {", tests: [T4("grants.test.js")] },
  { id: "s442 grants: `remove` does not cover pop / shift", file: `${SH}/analyze.scrml`,
    from: "            if (a == place || a == SeqAt.Anywhere) return true", to: "            if (a == place) return true", tests: [T4("grants.test.js")] },
  { id: "s442 grants: a removal judged by the GROW grant (append-only log pops)", file: `${SH}/analyze.scrml`,
    from: "        const isGranted: boolean = f.grants.replace || shrinkGranted(f.shrink, place)", to: "        const isGranted: boolean = f.grants.replace || f.grants.edits.length > 0", tests: [T4("grants.test.js")] },
  { id: "s442 grants: `filter` judged by the grow (`insert`) grant", file: `${SH}/analyze.scrml`,
    from: "        if (shape == 3) isGranted = f.grants.replace || shrinkGranted(f.shrink, SeqAt.Anywhere)\n", to: "", tests: [T4("grants.test.js")] },
  { id: "s442 grants: the retired `end` read as its grow half (guessed)", file: `${SH}/analyze.scrml`,
    from: "            \"end\"      :> GrantAxis.GRetired(\"append\", \"pop\")", to: "            \"end\"      :> GrantAxis.GGrow(SeqAt.End)", tests: [T4("grants.test.js")] },
  { id: "s442 grants: `pop` not recognized as a shrink grant", file: `${SH}/analyze.scrml`,
    from: "            \"pop\"      :> GrantAxis.GShrink(SeqAt.End)", to: "            \"pop\"      :> GrantAxis.GUnknown", tests: [T4("grants.test.js")] },
  { id: "s442 r1 F7: push onto a fixed-length sequence accepted (it grows)", file: `${SH}/analyze.scrml`,
    from: "        if (granted && growsFixed(p.ty)) return", to: "        if (false) return", tests: [T4("review-r1.test.js")] },
  { id: "s442 r1 F7: a growing shape on a fixed-length sequence accepted", file: `${SH}/analyze.scrml`,
    from: "        if (growsFixed(p.ty)) return addDiag(st, env.file, e.span, \"E-WRITE-INVARIANT\", fixedLengthMessage(f.sym.hint, shapeWhat(shape)))",
    to: "", tests: [T4("review-r1.test.js")] },
  // ---- s442 r2 ----
  { id: "s442 r2 item 1: O19 checked on the declaration only (a child's attribute silently dropped)", file: `${SH}/analyze.scrml`,
    from: "        for (const c of childFields(d.body)) { st = o19Diags(file, c, st) }", to: "", tests: [T4("review-r2.test.js")] },
  { id: "s442 r2 item 2: a removal on a fixed-length sequence accepted", file: `${SH}/analyze.scrml`,
    from: "        if (growsFixed(p.ty)) return addDiag(st, env.file, e.span, \"E-WRITE-INVARIANT\", fixedShrinkMessage(at.substring(1), what))", to: "", tests: [T4("review-r2.test.js")] },
  { id: "s442 r2 item 2: `filter` on a fixed-length sequence accepted", file: `${SH}/analyze.scrml`,
    from: "        if (shape == 3 && growsFixed(p.ty)) return", to: "        if (false) return", tests: [T4("review-r2.test.js")] },
  { id: "s442 r2 item 3: a duplicate grant token accepted", file: `${SH}/analyze.scrml`,
    from: "            if (seen.indexOf(g) >= 0) {", to: "            if (false) {", tests: [T4("review-r2.test.js")] },
  { id: "s442 r2 item 4: a sequence spread's elements read `@x` LIVE (no one snapshot)", file: `${SH}/lower.scrml`,
    from: "        for (const x of elems) { values = values.concat([lowerExpr(sc, x)]) }", to: "        for (const x of elems) { values = values.concat([lowerExpr(c, x)]) }", tests: [T4("review-r2.test.js")] },
  // ---- dpa-045 (RULED S442): the free-text production, interpolation extent, `\\"` deleted ----
  { id: "dpa-045 D: any `<` in free text opens a tag (`a < b` rejected)", file: `${SH}/parse.scrml`,
    from: "            } else if (chAt(m, 0) == \"<\" && opensTag(chAt(m, 1))) {", to: "            } else if (chAt(m, 0) == \"<\") {", tests: [T4("dpa045.test.js")] },
  { id: "dpa-045 B(1): a `}` inside a nested string ends it (strings no longer whole tokens to the interpolation walker)", file: `${SH}/lex.scrml`,
    from: "            } else if (code == closeCode) {\n                c = advance(c, 1)         // consume the closing quote",
    to: "            } else if (code == closeCode || code == 125) {\n                c = advance(c, 1)         // consume the closing quote", tests: [T4("dpa045.test.js")] },
  // (S444 "A for escapes": the display-text escapes are RESTORED — this row now
  // proves the lexer DECODES them: with the branch gone `\"` ends the literal)
  { id: "S444 ce-R2: the display-mode lexer does not decode `\\\"` / `\\\\` (a `\\` is content, `\"` closes)", file: `${SH}/lex.scrml`,
    from: "            if (dq && code == 92) {", to: "            if (false) {", tests: [T4("dpa045.test.js"), T4("comment-escapes.test.js")] },
  { id: "dpa-045 fu3: a `${…}` inside a display-text literal is not walked (a `\"` inside it ends the literal)", file: `${SH}/lex.scrml`,
    from: "            } else if (dq && code == 36 && peekCode(c, 1) == 123) {", to: "            } else if (false) {", tests: [T4("dpa045.test.js")] },
  { id: "dpa-045 B(3): display mode on in every region (a LOGIC string loses its JS escapes — `\\t`)", file: `${SH}/lex.scrml`,
    from: "        return lexFromMode(src, pos, stop, isCodeDefault(stop))", to: "        return lexFromMode(src, pos, stop, true)", tests: [T4("dpa045.test.js"), T4("comment-escapes.test.js")] },
  // s444 r2 fix 1, re-read under S444 "A for escapes": `\\"` is a VALID escape
  // again, so E-PARSE-001 must still never fire on it — these rows put it on.
  { id: "S444 ce-R2: E-PARSE-001 raised on the valid escape `\\\"` in a `:`-shorthand display-text literal", file: `${SH}/parse.scrml`,
    from: "        const tp: TP = codeRegionTP(mAdv(mp, 1), LexStop.Shorthand)\n",
    to: "        const tp0s: TP = codeRegionTP(mAdv(mp, 1), LexStop.Shorthand)\n        const tp: TP = mp.src.substring(mp.pos, lastEnd(tp0s) + 1).indexOf(\"\\\\\\\"\") >= 0 ? diagAt(tp0s, \"E-PARSE-001\", \"x\", cur(tp0s)) : tp0s\n",
    tests: [T4("dpa045.test.js"), T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: E-PARSE-001 raised on the valid escape `\\\"` in a code-default body's display-text literal", file: `${SH}/parse.scrml`,
    from: "                const tp0: TP = codeRegionTP(m, LexStop.CodeBody)\n",
    to: "                const tp0: TP = codeRegionTP(m, LexStop.CodeBody)\n                if (m.src.substring(m.pos, lastEnd(tp0)).indexOf(\"\\\\\\\"\") >= 0) m = mDiag(m, \"E-PARSE-001\", \"x\", m.pos, lastEnd(tp0))\n",
    tests: [T4("dpa045.test.js"), T4("comment-escapes.test.js")] },
  // ---- S444 (ruling:user-voice-scrml.md S444 "yes on // revised, A for escapes") ----
  // R1 — a free-text `//` is a comment only at line start / after whitespace; opaque to end of line
  { id: "S444 ce-R1: every free-text `//` is a comment again (the S442 reading — `http://x` loses `//x`)", file: `${SH}/parse.scrml`,
    from: "        return before == \" \" || before == \"\\t\" || before == \"\\n\" || before == \"\\r\"\n", to: "        return true\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R1: no `//` in free text is a comment (prose `a // b` rendered)", file: `${SH}/parse.scrml`,
    from: "            } else if (mLooking(m, \"//\") && freeTextCommentAt(m)) {", to: "            } else if (false) {", tests: [T4("comment-escapes.test.js"), T4("dpa045.test.js")] },
  { id: "S444 ce-R1: only a SPACE counts as whitespace (tab / newline-start `//` rendered)", file: `${SH}/parse.scrml`,
    from: "        return before == \" \" || before == \"\\t\" || before == \"\\n\" || before == \"\\r\"\n", to: "        return before == \" \"\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R1: the comment is NOT opaque — it ends at a `</` (bryan's `<p> // … </p>` closes at the first `</p>`)", file: `${SH}/parse.scrml`,
    from: "            } else if (mLooking(m, \"//\") && freeTextCommentAt(m)) {\n                m = skipLineComment(m)\n",
    to: "            } else if (mLooking(m, \"//\") && freeTextCommentAt(m)) {\n                const nl: int = m.src.indexOf(\"\\n\", m.pos)\n                const cl: int = m.src.indexOf(\"</\", m.pos)\n                m = mAt(m, cl >= 0 && (nl < 0 || cl < nl) ? cl : (nl < 0 ? m.src.length : nl))\n",
    tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R1: a CR is not a line terminator (the comment swallows the `\\r` of `\\r\\n`)", file: `${SH}/parse.scrml`,
    from: "        while (!mEof(m) && chAt(m, 0) != \"\\n\" && chAt(m, 0) != \"\\r\") { m = mAdv(m, 1) }", to: "        while (!mEof(m) && chAt(m, 0) != \"\\n\") { m = mAdv(m, 1) }", tests: [T4("comment-escapes.test.js")] },
  // R2 — `\"` `\\` `\${` restored in a display-text literal; any other `\` + char is E-PARSE-001
  { id: "S444 ce-R2: the lexer does not decode `\\${` (a standalone `\"a \\${ b\"` walks a runaway interpolation)", file: `${SH}/lex.scrml`,
    from: "                } else if (n1 == 36 && peekCode(c, 2) == 123) {", to: "                } else if (false) {", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: the lexer decodes only `\\\"` (`\\\\` stays two backslashes)", file: `${SH}/lex.scrml`,
    from: "                if (n1 == 34 || n1 == 92) {", to: "                if (n1 == 34) {", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: the parser's escape table drops `\\${` (splitDisplay interpolates it)", file: `${SH}/parse.scrml`,
    from: "        if (src.substring(i + 1, i + 3) == interpOpen()) return 3\n", to: "", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: the parser's escape table drops `\\\\` (`\"C:\\\\\"` at EOF reads as unterminated)", file: `${SH}/parse.scrml`,
    from: "        if (n == \"\\\"\" || n == \"\\\\\") return 2\n", to: "        if (n == \"\\\"\") return 2\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: splitDisplay does not decode the escapes", file: `${SH}/parse.scrml`,
    from: "            const esc: int = displayEscLen(m.src, m.pos)\n            if (esc > 0) {\n", to: "            const esc: int = 0\n            if (esc > 0) {\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: displayCloseAt ignores the escapes (an escaped `\\\"` closes — no E-CTX-001)", file: `${SH}/parse.scrml`,
    from: "            const c: string = src.substring(i, i + 1)\n            const esc: int = displayEscLen(src, i)\n",
    to: "            const c: string = src.substring(i, i + 1)\n            const esc: int = 0\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: hasLiveInterp is the raw `${` search (a nested `\\${` literal reported E-BOOTSTRAP-UNSUPPORTED)", file: `${SH}/parse.scrml`,
    from: "hasLiveInterp(m.src, t.start, t.end)) {", to: "t.text.indexOf(interpOpen()) >= 0) {", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: no E-PARSE-001 for a malformed escape in a `:`-shorthand literal", file: `${SH}/parse.scrml`,
    from: "        let m: MP = skipSpace(backToMarkup(mp, t))\n        if (isStandaloneDisplay(tp)) m = displayEscapeDiags(m, tp.toks)\n", to: "        let m: MP = skipSpace(backToMarkup(mp, t))\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: no E-PARSE-001 for a malformed escape in a state-child body literal", file: `${SH}/parse.scrml`,
    from: "                if (isStandaloneDisplay(tp)) m = displayEscapeDiags(m, tp.toks)\n", to: "", tests: [T4("comment-escapes.test.js")] },
  // S239 review of 5d5ad360b (nits 1 + 3)
  { id: "S444 ce-R1: a CR before `//` is not whitespace (a CR-only file's `\\r// c` rendered)", file: `${SH}/parse.scrml`,
    from: "        return before == \" \" || before == \"\\t\" || before == \"\\n\" || before == \"\\r\"\n", to: "        return before == \" \" || before == \"\\t\" || before == \"\\n\"\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: an unterminated literal's recovered content is not cooked (`\\\"` kept raw)", file: `${SH}/parse.scrml`,
    from: "            if (esc > 0 && i + esc <= to) {\n", to: "            if (false) {\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-R2: a malformed escape in an unterminated literal's recovered content not reported (`\"abc\\` at EOF)", file: `${SH}/parse.scrml`,
    from: "            } else if (c == \"\\\\\") {\n                const e: int = i + 2 <= to ? i + 2 : to\n", to: "            } else if (false) {\n                const e: int = i + 2 <= to ? i + 2 : to\n", tests: [T4("comment-escapes.test.js")] },
  // RULED S444 "standalone only": a code-default `"…"` is display text ONLY as a standalone body statement
  { id: "S444 ce-SA: every code-default region stays display-lexed (a nested `\"many\\n\"` gets E-PARSE-001)", file: `${SH}/parse.scrml`,
    from: "        if (isStandaloneDisplay(d)) return d\n", to: "        return d\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-SA: nothing is standalone (a lone `\"x\\n\"` is re-lexed as a logic string — no E-PARSE-001)", file: `${SH}/parse.scrml`,
    from: "        if (tp.toks.length != 2) return false\n", to: "        return false\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-SA: the E-PARSE-001 pass runs on a non-standalone state-body region", file: `${SH}/parse.scrml`,
    from: "                if (isStandaloneDisplay(tp)) m = displayEscapeDiags(m, tp.toks)\n", to: "                m = displayEscapeDiags(m, tp.toks)\n", tests: [T4("comment-escapes.test.js")] },
  { id: "S444 ce-SA: the lexer's explicit display flag ignored (lexFromMode always display)", file: `${SH}/lex.scrml`,
    from: "        let st: LexState = mkState(cursorAt(src, pos), LexMode.InCode, [], [], [], display)", to: "        let st: LexState = mkState(cursorAt(src, pos), LexMode.InCode, [], [], [], true)", tests: [T4("comment-escapes.test.js"), T4("dpa045.test.js")] },
  { id: "S444 ce-R2: the escape check reads INTO an interpolation (a logic `\\t` in `${\"…\"}` reported)", file: `${SH}/parse.scrml`,
    from: "                        const e: int = lexFrom(m.src, i + 1, LexStop.Balanced).end\n                        i = e > i + 1 ? e : i + 2\n", to: "                        i = i + 2\n", tests: [T4("comment-escapes.test.js")] },
  // ---- dpa-045 follow-ups (RULED S442): the closed exit set, display interpolation, whitespace kept ----
  { id: "dpa-045 fu1: `~{` not an exit of free text (SPEC §4.18.1b)", file: `${SH}/parse.scrml`,
    from: "        return c == \"^\" || c == \"!\" || c == \"~\"\n", to: "        return c == \"^\" || c == \"!\"\n", tests: [T4("dpa045.test.js")] },
  { id: "dpa-045 fu1: `?{` taken as an exit of free text (its §3.1 parent is Logic only)", file: `${SH}/parse.scrml`,
    from: "        return c == \"^\" || c == \"!\" || c == \"~\"\n", to: "        return c == \"^\" || c == \"!\" || c == \"~\" || c == \"?\"\n", tests: [T4("dpa045.test.js")] },
  { id: "dpa-045 fu1: `_{` in a markup body is text (E-FOREIGN-004 dropped)", file: `${SH}/parse.scrml`,
    from: "            } else if (foreignLevel(m) >= 0) {", to: "            } else if (false) {", tests: [T4("dpa045.test.js")] },
  { id: "dpa-045 fu1: `my_{c}` taken as a foreign opener (identifier-tail guard dropped)", file: `${SH}/parse.scrml`,
    from: "        if (isIdentTail(chAt(mp, -1))) return -1\n", to: "", tests: [T4("dpa045.test.js")] },
  { id: "dpa-045 fu1: a foreign block closes at the first `}` (level `=` count ignored)", file: `${SH}/parse.scrml`,
    from: "            if (c == \"}\" && depth == 0 && closesForeign(m, lvl)) {", to: "            if (c == \"}\" && depth == 0) {", tests: [T4("dpa045.test.js")] },
  { id: "dpa-045 fu1: a level-0 foreign block ignores brace depth", file: `${SH}/parse.scrml`,
    from: "                if (lvl == 0 && c == \"{\") depth = depth + 1\n", to: "", tests: [T4("dpa045.test.js")] },
  // s444 r2 fix 3: `?` / `!` in the tag-open class (§4.18.1b item 3)
  { id: "s444 r2 fix 3: `<?` is content (`?` dropped from the tag-open class)", file: `${SH}/parse.scrml`,
    from: "        return c == \"!\" || c == \"/\" || c == \"?\" || c == \"*\"", to: "        return c == \"!\" || c == \"/\" || c == \"*\"", tests: [T4("dpa045.test.js")] },
  { id: "s444 r2 fix 3: `<!` is content (`!` dropped from the tag-open class)", file: `${SH}/parse.scrml`,
    from: "        return c == \"!\" || c == \"/\" || c == \"?\" || c == \"*\"", to: "        return c == \"/\" || c == \"?\" || c == \"*\"", tests: [T4("dpa045.test.js")] },
  // s444 r2 fix 2: a `^{` / `!{` / `~{` block ends at its BALANCING `}` (§4.18.1b pin 3)
  { id: "s444 r2 fix 2: a `^{`/`!{`/`~{` block ends at the first raw `}` (a `}` inside a string ends it)", file: `${SH}/parse.scrml`,
    from: "return mDiag(mAt(m, lastEnd(tp)), \"E-BOOTSTRAP-UNSUPPORTED\", \"a `\" + chAt(mp, 0)",
    to: "return mDiag(mAt(m, mp.src.indexOf(\"}\", mp.pos) + 1), \"E-BOOTSTRAP-UNSUPPORTED\", \"a `\" + chAt(mp, 0)", tests: [T4("dpa045.test.js")] },
  // s444 r2 fix 4 + r3 (PA ruling): an unterminated display-text literal is E-CTX-001 (§4.18.3 / §4.18.7);
  // unterminated = no closing `"` before EOF (a `${…}` skipped by token depth); a CLOSED literal is never cut
  { id: "s444 r2 fix 4: the unterminated-literal check dropped (a state body)", file: `${SH}/parse.scrml`,
    from: "            } else if (chAt(m, 0) == \"\\\"\" && displayCloseAt(m.src, m.pos) < 0) {", to: "            } else if (false) {", tests: [T4("dpa045.test.js")] },
  { id: "s444 r2 fix 4: the unterminated-literal check dropped (a `:`-shorthand)", file: `${SH}/parse.scrml`,
    from: "        if (chAt(at, 0) == \"\\\"\" && displayCloseAt(mp.src, at.pos) < 0) {", to: "        if (false) {", tests: [T4("dpa045.test.js")] },
  { id: "s444 r3: the terminated-scan does not skip `${…}` (a `\"` in an interpolation's string closes the literal)", file: `${SH}/parse.scrml`,
    from: "                const e: int = lexFrom(src, i + 1, LexStop.Balanced).end\n                i = e > i + 1 ? e : i + 2\n", to: "                i = i + 2\n", tests: [T4("dpa045.test.js")] },
  { id: "s444 r3: a CLOSED literal searched for closers (the r2 regression: cut at `</>`)", file: `${SH}/parse.scrml`,
    from: "            } else if (chAt(m, 0) == \"\\\"\" && displayCloseAt(m.src, m.pos) < 0) {",
    to: "            } else if (chAt(m, 0) == \"\\\"\" && (displayCloseAt(m.src, m.pos) < 0 || firstBodyCloser(m.src, m.pos + 1, tag) < displayCloseAt(m.src, m.pos))) {", tests: [T4("dpa045.test.js")] },
  { id: "s444 r3: the named closer `</tag>` not a recovery point", file: `${SH}/parse.scrml`,
    from: "            if (src.substring(i, i + tag.length + 3) == \"</\" + tag + \">\") return i\n", to: "", tests: [T4("dpa045.test.js")] },
  { id: "s444 r3: recovery runs to end of file (a runaway literal eats the body closer)", file: `${SH}/parse.scrml`,
    from: "            if (src.substring(i, i + 3) == \"</>\") return i\n", to: "", tests: [T4("dpa045.test.js")] },
  { id: "dpa-045 fu1: `<_` / `<.` are content (scrml's own tag forms dropped from the class)", file: `${SH}/parse.scrml`,
    from: "        return c == \"!\" || c == \"/\" || c == \"?\" || c == \"*\" || c == \"_\" || c == \".\"", to: "        return c == \"!\" || c == \"/\" || c == \"?\" || c == \"*\"", tests: [T4("dpa045.test.js")] },
  { id: "dpa-045 fu3: a `${`-carrying display-text literal not split into its segments (§4.18.4)", file: `${SH}/parse.scrml`,
    from: "        if (isStandaloneDisplay(tp) && isDisplayTemplate(m.src, e)) {", to: "        if (false) {", tests: [T4("dpa045.test.js")] },
  { id: "dpa-045 fu4: L13 restored — whitespace-only text containing a newline dropped", file: `${SH}/lower.scrml`,
    from: "        if (t == \"\") return []\n        return [View.Text(t)]", to: "        if (t.trim() == \"\" && t.indexOf(\"\\n\") >= 0) return []\n        return [View.Text(t)]",
    tests: [T4("dpa045.test.js"), T2("lower.test.js")] },
  { id: "dpa-045 fu4: text runs trimmed (the spaces next to `${…}` deleted — 'liftedali')", file: `${SH}/lower.scrml`,
    from: "        if (t == \"\") return []\n        return [View.Text(t)]", to: "        if (t.trim() == \"\") return []\n        return [View.Text(t.trim())]",
    tests: [T4("dpa045.test.js")] },
  // ---- s442 r3: the O19 residue + the sub-field removal ----
  { id: "s442 r3: an own TYPE with no initializer plus attributes accepted (O19 silently decided)", file: `${SH}/analyze.scrml`,
    from: "        if ((hasOwnValue(d.own) || hasOwnType(d)) && d.attrs.length > 0) {", to: "        if (hasOwnValue(d.own) && d.attrs.length > 0) {", tests: [T4("review-r3.test.js")] },
  { id: "s442 r3: a removal on a sub-field sequence judged by the containing field", file: `${SH}/analyze.scrml`,
    from: "        if (p.path.length > 0) {\n            // r3: a removal", to: "        if (false) {\n            // r3: a removal", tests: [T4("review-r3.test.js")] },
  { id: "s442 r3: the sub-field removal message names the containing field (`@r`)", file: `${SH}/analyze.scrml`,
    from: "\"`\" + placeKey(m.obj) + \".\" + m.method + \"()` — an edit of a sub-field", to: "\"`@\" + f.sym.hint + \".\" + m.method + \"()` — an edit of a sub-field", tests: [T4("review-r3.test.js")] },
  // ---- s444 (PA addition): two fail-open shapes now fail closed ----
  { id: "s444 PA: a scrml structural element falls through to MHtml (rendered as markup, no diagnostic)", file: `${SH}/analyze.scrml`,
    from: "        if (owner != \"\") {\n            return addDiag(st, env.file, e.span, \"E-BOOTSTRAP-UNSUPPORTED\"", to: "        if (false) {\n            return addDiag(st, env.file, e.span, \"E-BOOTSTRAP-UNSUPPORTED\"", tests: [T4("failclosed.test.js")] },
  { id: "s444 PA: `<request>` dropped from the structural registry", file: `${SH}/analyze.scrml`,
    from: "            \"request\"       :> \"§6.7.7 async request\"\n", to: "", tests: [T4("failclosed.test.js")] },
  { id: "s444 PA: an unknown declaration-opener word silently ignored", file: `${SH}/analyze.scrml`,
    from: "            if (!isKnownOpenerWord(a.name) && a.name.indexOf(\":\") < 0) {", to: "            if (false) {", tests: [T4("failclosed.test.js")] },
  { id: "s444 PA: a program CELL's opener words not checked (persist= ignored there)", file: `${SH}/analyze.scrml`,
    from: "                        if (!isNestedUserDecl(c) && declNames.indexOf(ownTypeName(c)) < 0) st = openerWordDiags(", to: "                        if (false) st = openerWordDiags(", tests: [T4("failclosed.test.js")] },
  { id: "s444 PA: opener words after a parse error reported (recovery debris)", file: `${SH}/analyze.scrml`,
    from: "        if (hasErrIn(errs, d.span)) return st\n        for (const a of d.mods) {", to: "        for (const a of d.mods) {", tests: [T4("failclosed.test.js")] },
  // ---- s444 Phase A: the Core additions (bind, host call, Star, removals, index places, lambdas) ----
  { id: "s444 A1: `bind:` attributes refused again (resolveBind never reached)", file: `${SH}/analyze.scrml`,
    from: "            } else if (a.name.substring(0, 5) == \"bind:\") {", to: "            } else if (false) {", tests: [T4("audit.test.js"), T4("core-additions.test.js")] },
  { id: "s444 A1: a bind's element check dropped (`bind:value` on a <div> accepted)", file: `${SH}/analyze.scrml`,
    from: "        if (isValue && e.tag != \"input\" && e.tag != \"textarea\" && e.tag != \"select\") {", to: "        if (false) {", tests: [T4("core-additions.test.js")] },
  { id: "s444 A1: a bind's value/place type check dropped (bind:checked on a string)", file: `${SH}/analyze.scrml`,
    from: "            if (bad != \"\") return addDiag(st, env.file, a.span, \"E-TYPE-031\"", to: "            if (false) return addDiag(st, env.file, a.span, \"E-TYPE-031\"", tests: [T4("core-additions.test.js")] },
  { id: "s444 A1: O54 (a) — a child field's own renders not given its own name (`@email` unresolved)", file: `${SH}/analyze.scrml`,
    from: "st = resolveNodes(withOwn(renv, fd.name), rendersOf(fd), st)", to: "st = resolveNodes(withOwn(renv, \"\"), rendersOf(fd), st)", tests: [T4("form.test.js")] },
  { id: "s444 A1: lower drops the bind (Attr.Bind never built)", file: `${SH}/lower.scrml`,
    from: ":> [bindAttr(c, bk, w, d, x, sk)].concat(validatorAttrs(vs))", to: ":> [].concat(validatorAttrs(vs))", tests: [T4("audit.test.js"), T4("core-additions.test.js")] },
  { id: "s444 A1: bind:checked prints as the `value` property", file: `${SH}/print.scrml`,
    from: "            .Checked :> \"checked\"", to: "            .Checked :> \"value\"", tests: [T4("core-additions.test.js"), T4("form.test.js")] },
  { id: "s444 A1: the runtime bind never writes back (no input / change listener)", file: RT,
    from: "  on(scope, el, prop === \"checked\" ? \"change\" : \"input\", () => write(el[prop]));\n", to: "", tests: [T4("audit.test.js"), T4("core-additions.test.js")] },
  { id: "s444 A1: the runtime bind never shows the cell", file: RT,
    from: "    if (el[prop] !== shown) el[prop] = shown;\n", to: "", tests: [T4("audit.test.js"), T4("core-additions.test.js")] },
  { id: "s444 A1 C8: a bind reading one place and writing another is accepted", file: `${SH}/check.scrml`,
    from: "        if (got != exp) out = out.concat([\"C8: a bind reads \"", to: "        if (false) out = out.concat([\"C8: a bind reads \"", tests: [T4("core-additions.test.js")] },
  { id: "s444 A2: `Date.now()` in a pure `fn` accepted (E-FN-004 dropped)", file: `${SH}/analyze.scrml`,
    from: "            .HostPure :> diagX(env, e, \"E-FN-004\"", to: "            .HostPure :> diagX(env, e, \"E-BOOTSTRAP-UNSUPPORTED\"", tests: [T4("core-additions.test.js")] },
  { id: "s444 A2: a `fn` body gets the function host context", file: `${SH}/analyze.scrml`,
    from: "            if (fs.info.pure) host = HostCtx.HostPure\n", to: "", tests: [T4("core-additions.test.js")] },
  { id: "s444 A2: an event handler not a host-call context (`onclick=(@t = Date.now())` refused)", file: `${SH}/analyze.scrml`,
    from: "                st = resolveHandler(withHost(penv, HostCtx.HostOk), a.value, st)", to: "                st = resolveHandler(penv, a.value, st)", tests: [T4("core-additions.test.js")] },
  { id: "s444 A2: the host call printed wrong (`Date.now_()`)", file: `${SH}/print.scrml`,
    from: "            .DateNow :> jcall(jmember(jid(\"Date\"), \"now\"), [])", to: "            .DateNow :> jcall(jmember(jid(\"Date\"), \"now_\"), [])", tests: [T4("audit.test.js"), T4("core-additions.test.js")] },
  { id: "s444 A2: `Date` not a reserved emitted name (a user `function Date` shadows the host)", file: `${SH}/names.scrml`,
    from: "            \"Date\" :> true\n", to: "", tests: [T4("core-additions.test.js")] },
  { id: "s444 A3: `<*x/>` of a declaration inlined again (per-site instances, not the existing one)", file: `${SH}/analyze.scrml`,
    from: "        return addElem(st, e.nid, ElemFact.MStar(d.info.sym, InstRef.Shared(d.info.sym)))", to: "        return addElem(st, e.nid, ElemFact.MInline({ nodes: nodes, subst: InstRef.Shared(d.info.sym) }))", tests: [T4("review-r1.test.js"), T4("form.test.js"), T4("core-additions.test.js")] },
  { id: "s444 A3: a Star renders into the INSTANCE's scope (its view outlives the site)", file: `${SH}/print.scrml`,
    from: "[instJs(ctx, i), scopeVar(), node, JsExpr.JNull]", to: "[instJs(ctx, i), jmember(instJs(ctx, i), \"scope\"), node, JsExpr.JNull]", tests: [T4("core-additions.test.js")] },
  { id: "s444 A3: a prebuilt kid renders into its own instance scope (a Star site's kid view leaks)", file: `${SH}/print.scrml`,
    from: "        if (ctx.prebuilt) renderScope = scopeVar()\n", to: "", tests: [T4("core-additions.test.js")] },
  { id: "s444 A3 C10: a Star through another declaration's instance accepted", file: `${SH}/check.scrml`,
    from: "        if (target.sym.id != d.sym.id) return [\"C10: a Star of <\"", to: "        if (false) return [\"C10: a Star of <\"", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4: pop lowered as a FRONT removal", file: `${SH}/analyze.scrml`,
    from: "        if (m.method == \"pop\") edit = EditKind.RemoveEnd\n", to: "", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4: a removal lowered with count 2", file: `${SH}/lower.scrml`,
    from: "w.edit, Expr.Lit(Literal.Int(1)), w.check)]", to: "w.edit, Expr.Lit(Literal.Int(2)), w.check)]", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4: shrink grants not in the GrantSet (a shrink-only field has no capability)", file: `${SH}/analyze.scrml`,
    from: "        for (const a of g.shrink) { out = addEditOnce(out, seqShrinkEdit(a)) }\n", to: "", tests: [T4("core-additions.test.js"), T4("grants.test.js")] },
  { id: "s444 A4: `remove` does not cover end / front in the GrantSet (C3 then refuses the lowered pop)", file: `${SH}/analyze.scrml`,
    from: "        if (hasEditKind(out, EditKind.RemoveAnywhere)) {\n            out = addEditOnce(out, EditKind.RemoveEnd)", to: "        if (false) {\n            out = addEditOnce(out, EditKind.RemoveEnd)", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4: the filter shape lowered as a PositionWrite (not a shrink)", file: `${SH}/analyze.scrml`,
    from: "            if (shape == 3) return addEffect(st, e.nid, EffectFact.EWrite({ cap: cap, inst: p.inst, edit: EditKind.RemoveAnywhere", to: "            if (shape == 3) return addEffect(st, e.nid, EffectFact.EWrite({ cap: cap, inst: p.inst, edit: EditKind.PositionWrite", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4 runtime: removeEnd removes from the front", file: RT,
    from: "target.set(xs.slice(0, Math.max(0, xs.length - n)));", to: "target.set(xs.slice(n));", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4 runtime: removeFront removes nothing", file: RT,
    from: "export function removeFront(target, n) { target.set(target.peek().slice(n)); }", to: "export function removeFront(target, n) { target.set(target.peek().slice(0)); }", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4 C9: a removal count of 0 accepted", file: `${SH}/check.scrml`,
    from: "            .RemoveEnd :> countProblem(value)", to: "            .RemoveEnd :> \"\"", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4 index: an element field granting edits but no replace accepts `= v`", file: `${SH}/analyze.scrml`,
    from: "        if (!target.grants.replace) {\n            return addDiag(st, env.file, e.span, \"E-WRITE-NOT-GRANTED\"", to: "        if (false) {\n            return addDiag(st, env.file, e.span, \"E-WRITE-NOT-GRANTED\"", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4 index: no element-field grant in the GrantSet (a `Row[]` field has no capability)", file: `${SH}/analyze.scrml`,
    from: "        if (et is some) elemEdits = subFieldEdits(g, et)\n", to: "", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4 index runtime: an out-of-range position written (the sequence padded)", file: RT,
    from: "  if (!Number.isInteger(index) || index < 0 || index >= xs.length) {", to: "  if (false) {", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4 index C3: an ElemAt to an element field with no contract accepted", file: `${SH}/check.scrml`,
    from: "        if (targetGrants) return \"\"\n        return \"the target element field grants no write", to: "        return \"\"\n        return \"the target element field grants no write", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4 lambda: printed without its parameters", file: `${SH}/print.scrml`,
    from: "JsExpr.JArrowE(symNames(ctx, ps), exprJs(ctx, b))", to: "JsExpr.JArrowE([], exprJs(ctx, b))", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4 lambda: its parameters are not typed as the element (the typer sees Unknown)", file: `${SH}/analyze.scrml`,
    from: "            if (ty is some) st = addAnnot(st, rs.s, ty)\n", to: "", tests: [T4("core-additions.test.js")] },
  { id: "s444 A4 lambda: walk does not bind its parameters (no minted names)", file: `${SH}/walk.scrml`,
    from: "            .Lambda(params: ps) :> ps\n", to: "            .Lambda(params: ps) :> []\n", tests: [T4("core-additions.test.js")] },
  // ---- s444 Phase B: the dpa-058 build (RULED S442 items 1–5) ----
  { id: "s444 B: a bare validator word (`req`) read as an opener modifier again", file: `${SH}/parse.scrml`,
    from: "            if (isValidatorWord(a.name) && isNoValue(a.value)) {", to: "            if (false) {", tests: [T4("validators.test.js"), T4("form.test.js")] },
  { id: "s444 B: a `length(…)` comparison parsed as `>=` whatever was written", file: `${SH}/parse.scrml`,
    from: "            return { arg: AValArg.Cmp(op, r.e),", to: "            return { arg: AValArg.Cmp(\">=\", r.e),", tests: [T4("validators.test.js")] },
  { id: "s444 B: a regex's flags dropped by the parser (`/^a$/i` taken as exact)", file: `${SH}/parse.scrml`,
    from: "            const flags: string = rt.text.substring(last + 1)", to: "            const flags: string = \"\"", tests: [T4("validators.test.js")] },
  { id: "s444 B: a validator on an ELEMENT silently dropped", file: `${SH}/parse.scrml`,
    from: "        if (o.vals.length > 0) {", to: "        if (false) {", tests: [T4("validators.test.js")] },
  { id: "s444 B: `req` lowers to `required=\"required\"` (not the exact empty attribute)", file: `${SH}/analyze.scrml`,
    from: "        if (isStrLike(ty)) return valOk(v, [pair(\"required\", \"\")], st)", to: "        if (isStrLike(ty)) return valOk(v, [pair(\"required\", \"required\")], st)", tests: [T4("validators.test.js")] },
  { id: "s444 B: `length(>N)` lowered as minlength N (off by one)", file: `${SH}/analyze.scrml`,
    from: "        if (op == \">\") return valOk(v, [pair(\"minlength\", \"\" + (n + 1))], st)", to: "        if (op == \">\") return valOk(v, [pair(\"minlength\", \"\" + n)], st)", tests: [T4("validators.test.js")] },
  { id: "s444 B: a top-level `|` taken as exact in a pattern", file: `${SH}/analyze.scrml`,
    from: "                if (depth == 0) return false\n", to: "", tests: [T4("validators.test.js")] },
  { id: "s444 B: a pattern with flags taken as exact", file: `${SH}/analyze.scrml`,
    from: "        if (flags != \"\" || !exactPattern(src)) {", to: "        if (!exactPattern(src)) {", tests: [T4("validators.test.js")] },
  { id: "s444 B: `minlength` lowered onto a <select> (HTML gives it no meaning there)", file: `${SH}/analyze.scrml`,
    from: "        if (name == \"minlength\" || name == \"maxlength\") return tag == \"textarea\"", to: "        if (name == \"minlength\" || name == \"maxlength\") return true || tag == \"textarea\"", tests: [T4("validators.test.js")] },
  { id: "s444 B: a hand-written attribute does not win (the lowered one is added too)", file: `${SH}/analyze.scrml`,
    from: "                } else if (attrNamed(e.attrs, h.name) is not && !hasPairNamed(out, h.name)) {", to: "                } else if (!hasPairNamed(out, h.name)) {", tests: [T4("validators.test.js")] },
  { id: "s444 B (5): a validated field nothing binds accepted (dead validators kept)", file: `${SH}/analyze.scrml`,
    from: "                    if (f.vals.length > 0 && !hasBindKey(keys, ds.info.sym.id, i)) {", to: "                    if (false) {", tests: [T4("validators.test.js")] },
  { id: "s444 B (5): validators on a top-level scalar not reported as dead", file: `${SH}/analyze.scrml`,
    from: "        if (where == 2) {\n            return { vs: [], st: addDiag(st, file, vals[0].span, \"E-VALIDATOR-DEAD\"", to: "        if (false) {\n            return { vs: [], st: addDiag(st, file, vals[0].span, \"E-VALIDATOR-DEAD\"", tests: [T4("validators.test.js")] },
  { id: "s444 B (5): `@cell.isValid` on a top-level cell not E-VALIDITY-NO-SURFACE", file: `${SH}/analyze.scrml`,
    from: "            if (where == 2) return diagX(env, e, \"E-VALIDITY-NO-SURFACE\"", to: "            if (false) return diagX(env, e, \"E-VALIDITY-NO-SURFACE\"", tests: [T4("validators.test.js")] },
  { id: "s444 B: validators on a derived field accepted (E-DERIVED-WITH-VALIDATORS dropped)", file: `${SH}/analyze.scrml`,
    from: "        if (isDerived) {\n            return { vs: [], st: addDiag(st, file, vals[0].span, \"E-DERIVED-WITH-VALIDATORS\"", to: "        if (false) {\n            return { vs: [], st: addDiag(st, file, vals[0].span, \"E-DERIVED-WITH-VALIDATORS\"", tests: [T4("validators.test.js")] },
  { id: "s444 B (2): lower drops the lowered validator attributes", file: `${SH}/lower.scrml`,
    from: ":> [bindAttr(c, bk, w, d, x, sk)].concat(validatorAttrs(vs))", to: ":> [bindAttr(c, bk, w, d, x, sk)]", tests: [T4("validators.test.js")] },
  { id: "s444 B (3): lower drops `novalidate`", file: `${SH}/lower.scrml`,
    from: "        if (c.t.novalidate.indexOf(e.nid) >= 0) return [Attr.Static(\"novalidate\", \"\")]", to: "        if (false) return [Attr.Static(\"novalidate\", \"\")]", tests: [T4("validators.test.js")] },
  { id: "s444 B (3): a form's `novalidate` does not look through Stars / uses", file: `${SH}/analyze.scrml`,
    from: "        if (expansionCarries(cx, f)) return true\n", to: "", tests: [T4("validators.test.js")] },
  { id: "s444 B (3): a form's `novalidate` does not look through an inlined `<*f/>`", file: `${SH}/analyze.scrml`,
    from: "            .MInline(v: v) :> nodesCarry(cx, v.nodes)\n", to: "            .MInline(v: v) :> false\n", tests: [T4("validators.test.js")] },
  // ---- s444 r2 (S239 review of 16221b99a) ----
  { id: "s444 r2 F1: a form's `novalidate` does not look into its `<slot/>` content", file: `${SH}/analyze.scrml`,
    from: "            .MSlot :> slotCarries(cx)\n", to: "            .MSlot :> false\n", tests: [T4("validators.test.js")] },
  { id: "s444 r2 F1: slot content passed on through another declaration's slot not followed", file: `${SH}/analyze.scrml`,
    from: "seen: cx.seen, slot: u.owner, slotSeen:", to: "seen: cx.seen, slot: -1, slotSeen:", tests: [T4("validators.test.js")] },
  { id: "s444 r2 F5a: a form's `novalidate` does not look through a state view's arms", file: `${SH}/analyze.scrml`,
    from: "            .MStateView(v: v) :> nodesCarry(cx, stateArmNodes(v))\n", to: "            .MStateView(v: v) :> false\n", tests: [T4("validators.test.js")] },
  { id: "s444 B: a user declaration's OWN validators silently ignored", file: `${SH}/analyze.scrml`,
    from: "                    if (d.validators.length > 0) st = addDiag(st, s.file, d.validators[0].span,", to: "                    if (false) st = addDiag(st, s.file, d.validators[0].span,", tests: [T4("validators.test.js")] },
  { id: "s444 B: validators below a child field silently ignored", file: `${SH}/analyze.scrml`,
    from: "            if (g.validators.length > 0) st = addDiag(", to: "            if (false) st = addDiag(", tests: [T4("validators.test.js")] },
  { id: "s444 B: a validator's argument expressions are never typed (the typer misses nodes)", file: `${SH}/analyze.scrml`,
    from: "            ts = typeValidatorArgs(env, fd.validators, ts)\n", to: "", tests: [T4("typing.test.js")] },
  { id: "F8 wildcard inside an alternation not flagged", file: "scripts/lint-no-default-arm.js",
    from: "if (a.alts.length > 1 && a.alts.some(altIsWild)) {", to: "if (false) {", tests: [T("lint.test.js")] },
];

function run(tests, cwd) {
  const r = spawnSync("bun", ["test", ...tests], { cwd, encoding: "utf8", timeout: 300000 });
  const out = (r.stdout ?? "") + (r.stderr ?? "");
  const fail = /(\d+) fail/.exec(out);
  return { code: r.status, fails: fail ? Number(fail[1]) : -1 };
}

// The mutations run on a MIRROR, never on the source (review INFO: a SIGKILL
// mid-run must not leave source mutated). The mirror (inside the worktree's
// gitignored .tmp/, so node_modules resolves by walking up) holds a COPY of
// compiler/self-host-v2 and scripts/lint-no-default-arm.js, plus symlinks to
// what the copies import read-only (compiler/src, compiler/native-parser,
// compiler/SPEC.md). A mutation edits the mirror's file and restores it from
// the copy's original text; the mirror is deleted at the end.
const MIRROR = join(ROOT, ".tmp", `mutations-${process.pid}`);
rmSync(MIRROR, { recursive: true, force: true });
mkdirSync(join(MIRROR, "compiler"), { recursive: true });
mkdirSync(join(MIRROR, "scripts"), { recursive: true });
cpSync(join(ROOT, SH), join(MIRROR, SH), { recursive: true });
cpSync(join(ROOT, "scripts", "lint-no-default-arm.js"), join(MIRROR, "scripts", "lint-no-default-arm.js"));
for (const rel of ["compiler/src", "compiler/native-parser", "compiler/SPEC.md", "bunfig.toml", "package.json"]) {
  symlinkSync(join(ROOT, rel), join(MIRROR, rel));
}

// The gate's own proof: one mutation that cannot run, one that cannot bite.
const PROOF = process.env.MUTATIONS_PROOF ?? "";
const PROOFS = {
  absent: [{ id: "PROOF absent site", file: `${SH}/analyze.scrml`, from: "this text is not in analyze.scrml §§§", to: "", tests: [T2("typer.test.js")] }],
  harmless: [{ id: "PROOF harmless edit (a comment)", file: `${SH}/analyze.scrml`,
    from: "// self-host-v2 / analyze.scrml", to: "// self-host-v2 / analyze.scrml (harmless)", tests: [T2("typer-gap.test.js")] }],
};
// MUTATIONS_ONLY=<substring> runs only the rows whose id contains it (s444: a
// quick check of a new batch; the full run is still THE GATE).
const ONLY = process.env.MUTATIONS_ONLY ?? "";
const SET = (PROOF === "" ? MUTATIONS : PROOFS[PROOF])?.filter((m) => ONLY === "" || m.id.includes(ONLY));
if (!SET) throw new Error(`unknown MUTATIONS_PROOF=${PROOF}`);

const t0 = performance.now();
const results = [];
let bad = 0;
try {
  for (const m of SET) {
    const path = join(MIRROR, m.file);
    const orig = readFileSync(path, "utf8");
    const n = orig.split(m.from).length - 1;
    if (n !== 1) { results.push(`| ${m.id} | mutation site found ${n}× — NOT RUN |`); bad = bad + 1; continue; }
    try {
      writeFileSync(path, orig.replace(m.from, m.to));
      const r = run(m.tests, MIRROR);
      const red = r.code !== 0 && r.fails > 0;
      if (!red) bad = bad + 1;
      results.push(`| ${m.id} | ${red ? "RED" : "GREEN (does not bite!)"} (${r.fails} failing) |`);
    } finally {
      writeFileSync(path, orig);
    }
  }
  console.log("| mutation | result |\n|---|---|\n" + results.join("\n"));
  if (PROOF === "") {
    const clean = run([`./${SH}/slice-m1/`, `./${SH}/slice-m2/`, `./${SH}/slice-m4/`], MIRROR);
    console.log(`unmutated slice suite (on the mirror): exit ${clean.code}, ${clean.fails} failing`);
    if (clean.code !== 0) bad = bad + 1;
  }
} finally {
  rmSync(MIRROR, { recursive: true, force: true });
}
console.log(`${SET.length} mutation(s), ${bad} problem(s), wall ${((performance.now() - t0) / 1000).toFixed(1)} s`);
if (bad > 0) process.exitCode = 1;
